рестораны-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 12:52:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Рестораны`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Рестораны` (
  `idРесторана` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `Адрес` VARCHAR(200) NULL,
  `телефон` VARCHAR(20) NULL,
  `кухня` VARCHAR(50) NULL,
  `рейтинг` DECIMAL(3,2) NULL,
  PRIMARY KEY (`idРесторана`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Блюда`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Блюда` (
  `idБлюда` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `Цена` DECIMAL(10,2) NOT NULL,
  `время_приготовления` INT NULL,
  `Блюдаcol` VARCHAR(45) NULL,
  `idРесторана` INT NULL,
  PRIMARY KEY (`idБлюда`),
  INDEX `fk_Блюда_Рестораны1_idx` (`idРесторана` ASC) VISIBLE,
  CONSTRAINT `fk_Блюда_Рестораны1`
    FOREIGN KEY (`idРесторана`)
    REFERENCES `mydb`.`Рестораны` (`idРесторана`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ингредиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ингредиенты` (
  `idИнгредиента` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(45) NOT NULL,
  `цена_за_единицу` DECIMAL(10,2) NULL,
  `Поставщик` VARCHAR(100) NULL,
  PRIMARY KEY (`idИнгредиента`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Состав_блюда`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Состав_блюда` (
  `idБлюда` INT NULL,
  `idИнгредиента` INT NULL,
  `КоличествоИнгридиента` DECIMAL(10,3) NOT NULL,
  INDEX `ингридиент_idx` (`idИнгредиента` ASC) VISIBLE,
  INDEX `fk_Состав_блюда_Блюда1_idx` (`idБлюда` ASC) VISIBLE,
  PRIMARY KEY (`КоличествоИнгридиента`),
  CONSTRAINT `ингридиент`
    FOREIGN KEY (`idИнгредиента`)
    REFERENCES `mydb`.`Ингредиенты` (`idИнгредиента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Состав_блюда_Блюда1`
    FOREIGN KEY (`idБлюда`)
    REFERENCES `mydb`.`Блюда` (`idБлюда`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Курьеры`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Курьеры` (
  `idКурьера` INT NOT NULL AUTO_INCREMENT,
  `Фамилия` VARCHAR(50) NOT NULL,
  `Имя` VARCHAR(45) NOT NULL,
  `Отчество` VARCHAR(50) NULL,
  `Телефон` VARCHAR(20) NULL,
  `Транспорт` VARCHAR(20) NULL,
  `Статус` VARCHAR(20) NULL,
  PRIMARY KEY (`idКурьера`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Заказы_доставка`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Заказы_доставка` (
  `idЗаказа` INT NOT NULL AUTO_INCREMENT,
  `Дата` DATE NOT NULL,
  `Время` TIME NOT NULL,
  `Клиент` VARCHAR(100) NOT NULL,
  `АдресДоставки` VARCHAR(200) NULL,
  `Статус` VARCHAR(20) NULL,
  `Сумма` DECIMAL(10,2) NULL,
  `Ресторан` INT NULL,
  `Курьер` INT NULL,
  PRIMARY KEY (`idЗаказа`),
  INDEX `Курьер_idx` (`Курьер` ASC) VISIBLE,
  INDEX `Ресторан_idx` (`Ресторан` ASC) VISIBLE,
  CONSTRAINT `Курьер`
    FOREIGN KEY (`Курьер`)
    REFERENCES `mydb`.`Курьеры` (`idКурьера`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ресторан`
    FOREIGN KEY (`Ресторан`)
    REFERENCES `mydb`.`Рестораны` (`idРесторана`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Позиции_заказа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Позиции_заказа` (
  `Блюдо` INT NULL,
  `idЗаказа` INT NULL,
  `Количество` INT NOT NULL,
  PRIMARY KEY (`Количество`),
  INDEX `idЗаказа_idx` (`idЗаказа` ASC) VISIBLE,
  INDEX `idБлюдо_idx` (`Блюдо` ASC) VISIBLE,
  CONSTRAINT `idБлюдо`
    FOREIGN KEY (`Блюдо`)
    REFERENCES `mydb`.`Блюда` (`idБлюда`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idЗаказа`
    FOREIGN KEY (`idЗаказа`)
    REFERENCES `mydb`.`Заказы_доставка` (`idЗаказа`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
